# Site settings
title: i
email: ihowe@outlook.com
description: Welcome to my blog!

baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://haroel.github.io/i/" # the base hostname & protocol for your site
twitter_username: null
github_username:  haroel

# Build settings
markdown: kramdown
